# Generated by Django 5.1.3 on 2024-11-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sppc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso_liquido',
            field=models.DecimalField(db_column='peso_liquido', db_comment='Capacidade da embalagem do produto em peso ou liquido.', decimal_places=4, max_digits=8, verbose_name='Peso/liquido do produto'),
        ),
    ]
