# Generated by Django 5.1.3 on 2024-11-26 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sppc', '0003_alter_consumidor_abdomen_alter_consumidor_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='acido',
            field=models.BooleanField(blank=True, db_column='acido', db_comment='Questiona se o consumidor, paciente ou cliente faz uso de ácido.', verbose_name='Faz uso de ácido?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='alergia',
            field=models.BooleanField(blank=True, db_column='alergia', db_comment='Questiona se o consumidor, paciente ou cliente possui alguma alergia.', verbose_name='Possui alguma alergia?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='alteracao_cardiaca',
            field=models.BooleanField(blank=True, db_column='alteracao_cardiaca', db_comment='Questiona se o consumidor, paciente ou cliente possui alterações ou oscilações cardiácas.', verbose_name='Possui alterações ou oscilações cardiácas?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='ciclo_intestinal_regular',
            field=models.BooleanField(blank=True, db_column='ciclo_intestinal_regular', db_comment='Questiona se o consumidor, paciente ou cliente está com o ciclo menstrual regular.', verbose_name='Ciclo de menstruação regular?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='cirurgia_recente',
            field=models.BooleanField(blank=True, db_column='cirurgia_recente', db_comment='Questiona se o consumidor, paciente ou cliente fez alguma cirurgia recente.', verbose_name='Fez alguma cirurgia recente?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='diabetes',
            field=models.BooleanField(blank=True, db_column='diabetes', db_comment='Questiona se o consumidor, paciente ou cliente possui diabetes.', verbose_name='Possui diabetes?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='disturbio_circulatorio',
            field=models.BooleanField(blank=True, db_column='disturbio_circulatorio', db_comment='Questiona se o consumidor, paciente ou cliente possui algum distúrbio circulátorio.', verbose_name='Possui algum distúrbio circulátorio?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='disturbio_hormonal',
            field=models.BooleanField(blank=True, db_column='disturbio_hormonal', db_comment='Questiona se o consumidor, paciente ou cliente possui distúrbio hormonal.', verbose_name='Possui distúrbio hormonal?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='disturbio_renal',
            field=models.BooleanField(blank=True, db_column='disturbio_renal', db_comment='Questiona se o consumidor, paciente ou cliente possui distúrbio renal.', verbose_name='Possui distúrbio renal?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='epiletico',
            field=models.BooleanField(blank=True, db_column='epiletico', db_comment='Questiona se o consumidor, paciente ou cliente é epiláptico(a).', verbose_name='É epilético(a)?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='fumante',
            field=models.BooleanField(blank=True, db_column='fumante', db_comment='Questiona se o consumidor, paciente ou cliente é fumante.', verbose_name='É fumante?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='funcionamento_intestinal_regular',
            field=models.BooleanField(blank=True, db_column='funcionamento_intestinal_regular', db_comment='Questiona se o consumidor, paciente ou cliente está com o funcionamento instestinal regular.', verbose_name='Funcionamento intestinal regular?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='gestante',
            field=models.BooleanField(blank=True, db_column='gestante', db_comment='Questiona se o consumidor, paciente ou cliente é gestante.', verbose_name='É gestante?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='hipertensao',
            field=models.BooleanField(blank=True, db_column='hipertensao', db_comment='Questiona se o consumidor, paciente ou cliente possui hipertensão ou pressão alta.', verbose_name='Possui hipertensão ou pressão alta?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='hipotensao',
            field=models.BooleanField(blank=True, db_column='hipotensao', db_comment='Questiona se o consumidor, paciente ou cliente possui hipotensão ou pressão baixa.', verbose_name='Possui hipotensão ou pressão baixa?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='ortopedico',
            field=models.BooleanField(blank=True, db_column='ortopedico', db_comment='Questiona se o consumidor, paciente ou cliente possui algum problema ortopédico.', verbose_name='Possui algum problema ortopédico?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='outro_problema',
            field=models.BooleanField(blank=True, db_column='outro_problema', db_comment='Questiona se o consumidor, paciente ou cliente possui algum outro problema que seja necessário relatar.', verbose_name='Possui algum outro problema que seja necessário relatar?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='problema_pele',
            field=models.BooleanField(blank=True, db_column='problema_pele', db_comment='Questiona se o consumidor, paciente ou cliente possui algum problema de pele.', verbose_name='Possui algum problema de pele?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='protese_corporal_facial',
            field=models.BooleanField(blank=True, db_column='protese_corporal_facial', db_comment='Questiona se o consumidor, paciente ou cliente possui alguma prótese corporal ou facial.', verbose_name='Possui prótese corporal ou facial?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='semanas_gestante',
            field=models.SmallIntegerField(db_column='semanas_gestante', db_comment='Questiona quantas semanas de gestação o consumidor, paciente ou cliente tem.', default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Quantas semanas de gestação'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='tratamento_medico',
            field=models.BooleanField(blank=True, db_column='tratamento_medico', db_comment='Questiona se o consumidor, paciente ou cliente está em algum tratamento médico.', verbose_name='Está em algum tratamento médico?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='tumor_lesao_precancerosa',
            field=models.BooleanField(blank=True, db_column='tumor_lesao_precancerosa', db_comment='Questiona se o consumidor, paciente ou cliente possui alguma tumor ou lesão pré-cancerosa.', verbose_name='Possui algum tumor ou lesão pré-cancerosa?'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='varizes_lesoes',
            field=models.BooleanField(blank=True, db_column='varizes_lesoes', db_comment='Questiona se o consumidor, paciente ou cliente possui varizes ou lesões.', verbose_name='Possui varizes ou lesões'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='data_fim',
            field=models.DateField(db_column='data_fim', db_comment='Data do fim do tratamento do consumidor, paciente ou cliente.', null=True, verbose_name='Data de fim do tratamento'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='eficaz',
            field=models.BooleanField(db_column='eficaz', db_comment='Questiona se o tratamendo no consumidor, paciente ou cliente foi eficaz.', null=True, verbose_name='Tratamento foi eficaz?'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='peso_final',
            field=models.DecimalField(blank=True, db_column='peso_final', db_comment='Qual peso final do consumidor, paciente ou cliente.', decimal_places=4, max_digits=8, null=True, verbose_name='Qual peso final em quilograma (Kg)?'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='peso_inicial',
            field=models.DecimalField(blank=True, db_column='peso_inicial', db_comment='Qual peso inicial do consumidor, paciente ou cliente.', decimal_places=4, max_digits=8, null=True, verbose_name='Qual peso inicial em quilograma (Kg)?'),
        ),
    ]
