# Generated by Django 5.1.3 on 2024-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sppc', '0005_alter_tratamento_data_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principioativo',
            name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='principios_ativos',
            field=models.ManyToManyField(to='api_sppc.principioativo'),
        ),
    ]
