# Generated by Django 5.1.3 on 2024-11-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sppc', '0006_remove_principioativo_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='culote',
            field=models.DecimalField(db_column='culote', db_comment='Qual tamanho do culote do consumidor, paciente ou cliente.', decimal_places=4, max_digits=8, verbose_name='Qual tamanho do culote em milimetros (mm)?'),
        ),
    ]
